openapi: 3.0.1
info:
  title: caraml/upi/v1/upi.proto
  version: version not set
servers:
- url: /
tags:
- name: UniversalPredictionService
paths:
  /v1/predict:
    post:
      operationId: UniversalPredictionService_PredictValues
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1PredictValuesRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/v1PredictValuesResponse'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      tags:
      - UniversalPredictionService
      x-codegen-request-body-name: body
components:
  schemas:
    protobufAny:
      additionalProperties:
        type: object
      properties:
        '@type':
          type: string
      type: object
    rpcStatus:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          type: array
      type: object
    v1ModelMetadata:
      example:
        name: name
        version: version
      properties:
        name:
          title: Model name that produce prediction
          type: string
        version:
          title: Model version that produce prediction
          type: string
      type: object
    v1NamedValue:
      example:
        stringValue: stringValue
        name: name
        integerValue: integerValue
        doubleValue: 0.8008281904610115
        type: null
      properties:
        name:
          title: |-
            Name describing what the value represents.
            Uses include:
            - Ensuring ML models process columns in the correct order
            - Defining a Feast row entity name
            - Parsing metadata to apply traffic rules
          type: string
        type:
          $ref: '#/components/schemas/v1NamedValueType'
        doubleValue:
          format: double
          type: number
        integerValue:
          format: int64
          type: string
        stringValue:
          type: string
      title: "Represents a named and typed data point.\nCan be used as a prediction\
        \ input, output or metdadata.\nOneof types are avoided as these can be difficult\
        \ to handle"
      type: object
    v1NamedValueType:
      default: TYPE_UNSPECIFIED
      enum:
      - TYPE_UNSPECIFIED
      - TYPE_DOUBLE
      - TYPE_INTEGER
      - TYPE_STRING
      type: string
    v1PredictValuesRequest:
      properties:
        predictionRows:
          items:
            $ref: '#/components/schemas/v1PredictionRow'
          title: "Collection of prediction instances to be predicted.\nEach prediction\
            \ row correspond to one prediction instance.\nNOTE: the ordering of prediction_rows\
            \ might differ with prediction_result_rows in the response"
          type: array
        targetName:
          title: |-
            Name of the concept we wish to predict.
            For example in context of iris classification problem it can be "iris-species"
          type: string
        predictionContext:
          items:
            $ref: '#/components/schemas/v1NamedValue'
          title: "Prediction context may contain additional data applicable to all\
            \ prediction instances\nFor example it can be used to store information\
            \ for traffic rules, experimentation\nor tracking purposes.\nEg. country_code,\
            \ service_type, service_area_id"
          type: array
        metadata:
          $ref: '#/components/schemas/v1RequestMetadata'
      title: Represents a request to predict multiple values
      type: object
    v1PredictValuesResponse:
      example:
        targetName: targetName
        metadata:
          models:
          - name: name
            version: version
          - name: name
            version: version
          experimentId: experimentId
          predictionId: predictionId
          treatmentId: treatmentId
        predictionContext:
        - stringValue: stringValue
          name: name
          integerValue: integerValue
          doubleValue: 0.8008281904610115
          type: null
        - stringValue: stringValue
          name: name
          integerValue: integerValue
          doubleValue: 0.8008281904610115
          type: null
        predictionResultRows:
        - values:
          - stringValue: stringValue
            name: name
            integerValue: integerValue
            doubleValue: 0.8008281904610115
            type: null
          - stringValue: stringValue
            name: name
            integerValue: integerValue
            doubleValue: 0.8008281904610115
            type: null
          rowId: rowId
        - values:
          - stringValue: stringValue
            name: name
            integerValue: integerValue
            doubleValue: 0.8008281904610115
            type: null
          - stringValue: stringValue
            name: name
            integerValue: integerValue
            doubleValue: 0.8008281904610115
            type: null
          rowId: rowId
      properties:
        predictionResultRows:
          items:
            $ref: '#/components/schemas/v1PredictionResultRow'
          title: "Prediction results corresponding to the\nprediction rows provided\
            \ in the request. \nNOTE: the ordering of prediction_result_rows might\
            \ differ with prediction_rows in the request"
          type: array
        targetName:
          title: Target name as defined in the request metadata
          type: string
        predictionContext:
          items:
            $ref: '#/components/schemas/v1NamedValue'
          title: Extensible field to cover unforeseen requirements
          type: array
        metadata:
          $ref: '#/components/schemas/v1ResponseMetadata'
      type: object
    v1PredictionResultRow:
      example:
        values:
        - stringValue: stringValue
          name: name
          integerValue: integerValue
          doubleValue: 0.8008281904610115
          type: null
        - stringValue: stringValue
          name: name
          integerValue: integerValue
          doubleValue: 0.8008281904610115
          type: null
        rowId: rowId
      properties:
        rowId:
          title: Row ID defined by the caller used to join a prediction result with
            a prediction row
          type: string
        values:
          items:
            $ref: '#/components/schemas/v1NamedValue'
          title: "Represents the predicted values corresponding to a \nsingle prediction\
            \ row. This will often be the output of an ML model.\nThis field is repeated\
            \ to support multi-task models with non-scalar outputs"
          type: array
      type: object
    v1PredictionRow:
      properties:
        rowId:
          description: "Row ID is defined by the client and can be used\nto join a\
            \ prediction row with the prediction result,\nand to track predictions\
            \ generated by multiple models.\nThe user is expected include row ID (along\
            \ with prediction ID)\nwhen calling the observations API so that predictions\n\
            and observations can be joined."
          type: string
        modelInputs:
          description: "Model inputs contain all preprocessed feature that model use\
            \ to perform prediction.\nThe feature ordering in model_inputs must be\
            \ the same as feature order expected by model. \nModel inputs can be populated\
            \ via 3 ways:\n- By performing preprocessing in the client-side and sent\
            \ as part of original request.\n- By transforming raw feature values stored\
            \ in transformer_inputs.\n- By retrieving precomputed feature value from\
            \ feature store."
          items:
            $ref: '#/components/schemas/v1NamedValue'
          type: array
        transformerInputs:
          description: "Transformer input contains raw values that can be used to\
            \ enrich model_inputs using transformer.\nTypically transformer_inputs\
            \ contains:\n- unprocessed/raw features that requires further processing.\
            \ \n- list of entities for which their precomputed features are retrieved\
            \ from feature store."
          items:
            $ref: '#/components/schemas/v1NamedValue'
          type: array
      title: |-
        Represents an single instance we wish to predict.
        Eg. for Matchmaking a prediction row will typically
        correspond to a proposed driver plan
      type: object
    v1RequestMetadata:
      properties:
        predictionId:
          title: "Unique identifier for each request. Optional.\nPrediction ID will\
            \ generated by the platform. The user is expected\ninclude the prediction\
            \ ID (along with row ID) when calling\nthe observations API so that predictions\
            \ and observations can be joined.\nPrediction ID is needed because row\
            \ ID may not be globally unique\nacross requests (only locally unique\
            \ within each request).\nIf there are experiments with alternative models,\
            \ the mapping\nfrom prediciton ID to treatment ID will be logged by the\
            \ platform"
          type: string
        requestTimestamp:
          format: date-time
          title: Timestamp of the request
          type: string
      type: object
    v1ResponseMetadata:
      example:
        models:
        - name: name
          version: version
        - name: name
          version: version
        experimentId: experimentId
        predictionId: predictionId
        treatmentId: treatmentId
      properties:
        predictionId:
          title: "Prediction ID generated by the platform. \nThe user is expected\
            \ include the prediction ID (along with row ID) when calling\nthe observations\
            \ API so that predictions and observations can be joined.\nPrediction\
            \ ID is needed because row ID may not be globally unique\nacross requests\
            \ (only locally unique within each request).\nIf there are experiments\
            \ with alternative models, the mapping\nfrom prediciton ID to treatment\
            \ ID will be logged by the platform"
          type: string
        models:
          items:
            $ref: '#/components/schemas/v1ModelMetadata'
          title: "List of model that produces the prediction \nThis field is repeated\
            \ to cater for use case such as ensembling several model production results"
          type: array
        experimentId:
          title: Optional experimentation metadata
          type: string
        treatmentId:
          type: string
      type: object
x-original-swagger-version: "2.0"
