name: Publish Benchmark
on:
  push:
    branches:
      - master
jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"
      - name: Install dependencies
        working-directory: ./gen/python/grpc
        run: pip install -e .[test]
      - name: Run test
        working-directory: ./gen/python/grpc
        run: pytest --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: ./gen/python/grpc/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
